### ISSUE TITLE
NoMethodError: undefined method `empty?' when activating an integer id

### ISSUE THREAD

**Issue by clinejj** [optimizely/ruby-sdk#101]
It looks like #63 introduced an error where the `DecisionService#get_variation` calls `get_forced_variation`, which doesn't validate that the user ID is a string before calling `empty?` at https://github.com/optimizely/ruby-sdk/blob/master/lib/optimizely/project_config.rb#L279

This leads to a NoMethodError when trying to activate an experiment or getting a variation for an integer based user id. https://github.com/optimizely/ruby-sdk/pull/93 fixed some of these validations, but not all of them.

**Comment by mikeng13** [comment]
@clinejj thanks for submitting this issue! Can you please tell us which version of the SDK you are using? We will look into this shortly.

**Comment by clinejj** [comment]
@mikeng13 This is on 2.0.0 release. We did not see this issue with the 2.0.0.beta

**Comment by mikeng13** [comment]
@clinejj thanks, I've logged an internal ticket for us to look into it and will prioritize with the team accordingly.

**Comment by clinejj** [comment]
We've mitigated the issue for now by updating our calls to pass in a string rather than an integer. Do you know if this will impact segmentation? (eg would the same value for an integer or string potentially get different values)?

**Comment by mikeng13** [comment]
Yeah it does make a difference because our event endpoint expects a `string` for `user_id` and if you pass in anything other than a string we might end up discarding the event altogether. Here are the docs for that endpoint: https://developers.optimizely.com/x/events/api/index.html#api_reference

That said, we should improve our docs by explicitly mentioning that the `user_id` param HAS to be a string. Regardless, the SDK shouldn't have thrown an error so we'll be patching that.

**Comment by mikeng13** [comment]
Fixed by https://github.com/optimizely/ruby-sdk/releases/tag/v2.0.1
